-- DDL: create the customers table

CREATE TABLE customers (
	id BIGINT, 
	year_birth BIGINT, 
	education TEXT, 
	marital_status TEXT, 
	income FLOAT(53), 
	kidhome BIGINT, 
	teenhome BIGINT, 
	dt_customer TEXT, 
	recency BIGINT, 
	mntwines BIGINT, 
	mntfruits BIGINT, 
	mntmeatproducts BIGINT, 
	mntfishproducts BIGINT, 
	mntsweetproducts BIGINT, 
	mntgoldprods BIGINT, 
	numdealspurchases BIGINT, 
	numwebpurchases BIGINT, 
	numcatalogpurchases BIGINT, 
	numstorepurchases BIGINT, 
	numwebvisitsmonth BIGINT, 
	acceptedcmp3 BIGINT, 
	acceptedcmp4 BIGINT, 
	acceptedcmp5 BIGINT, 
	acceptedcmp1 BIGINT, 
	acceptedcmp2 BIGINT, 
	response BIGINT, 
	complain BIGINT, 
	country TEXT, 
	age BIGINT, 
	total_spend BIGINT, 
	total_purchase BIGINT, 
	children BIGINT, 
	customer_tenure BIGINT, 
	avg_order_value FLOAT(53), 
	web_conversion_rate FLOAT(53), 
	age_band TEXT, 
	income_band TEXT, 
	seg_high_income BIGINT, 
	seg_young_customer BIGINT, 
	seg_campaign_responder BIGINT, 
	seg_high_web BIGINT, 
	seg_family BIGINT, 
	seg_high_spender BIGINT
)

;
